#!/usr/bin/env node
import { realpathSync } from 'node:fs'
import { readFile, writeFile, access } from 'node:fs/promises'
import { resolve, dirname, sep } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { createInterface } from 'node:readline/promises'
import { Writable } from 'node:stream'
import { parseDocument, stringify } from 'yaml'
import { Config, resolveConfig, normalizeList } from '../lib/config.js'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
export function splitList(text) {
  return normalizeList(text.split(/[,，\s]+/u))
}
export function createOverlay(config, bundle = false) {
  const row = { id: 'qq-bot', config }
  return bundle ? [row] : [{ insert: [{ ...row, name: resolve(root, 'lib/index.js').split(sep).join('/') }] }]
}
export function readConfig(text) {
  const document = parseDocument(text, { strict: true })
  if (document.errors.length || document.warnings.length) throw new Error('不支持的 YAML 配置。')
  const rows = document.toJS({ maxAliasCount: 100 })
  if (!Array.isArray(rows)) throw new Error('配置必须是 Cordis patch 数组。')
  const matches = rows.flatMap((row) => [row, ...(Array.isArray(row?.insert) ? row.insert : [])])
    .filter((row) => row?.id === 'qq-bot')
  if (matches.length !== 1) throw new Error('配置应包含唯一的 id: qq-bot 条目。')
  return matches[0].config ?? {}
}
export async function saveOverlay(path, config, bundle = false) {
  await writeFile(path, '# Generated by dsh-qq-bot setup\n' + stringify(createOverlay(config, bundle)), { flag: 'wx', mode: 0o600 })
}
async function setup(path, bundle) {
  try {
    await access(path)
    throw new Error('目标配置已存在；请编辑原文件，或用 --output 指定新文件。不会覆盖现有配置。')
  } catch (error) { if (error.code !== 'ENOENT') throw error }
  if (!process.stdin.isTTY || !process.stdout.isTTY) throw new Error('配置向导需要交互式终端。自动部署请使用示例配置和环境变量。')
  let hidden = false
  const output = new Writable({ write(chunk, encoding, callback) { if (!hidden) process.stdout.write(chunk, encoding); callback() } })
  const rl = createInterface({ input: process.stdin, output, terminal: true })
  rl.on('SIGINT', () => { rl.close() })
  const ask = async (prompt, secret = false) => {
    if (secret) process.stdout.write(prompt)
    hidden = secret
    try { return (await rl.question(secret ? '' : prompt)).trim() }
    finally {
      if (secret) rl.history = []
      hidden = false
      if (secret) process.stdout.write('\n')
    }
  }
  const yesNo = async (prompt, fallback) => {
    for (;;) {
      const answer = (await ask(prompt)).toLowerCase()
      if (!answer) return fallback
      if (['y', 'yes', '是'].includes(answer)) return true
      if (['n', 'no', '否'].includes(answer)) return false
      console.log('请输入 y 或 n。')
    }
  }
  try {
    console.log('QQ 机器人配置向导（默认仅白名单可访问）')
    const env = await yesNo('凭据从环境变量读取？[Y/n] ', true)
    const config = { enabled: true }
    if (!env) {
      do { config.appId = await ask('AppID：') } while (!config.appId)
      do { config.clientSecret = await ask('AppSecret（隐藏输入）：', true) } while (!config.clientSecret)
    }
    config.sandbox = await yesNo('使用 QQ 沙箱环境？[y/N] ', false)
    config.publicMode = false
    config.allowGroups = splitList(await ask('允许的 group_openid（逗号分隔；未知可留空）：'))
    config.allowUsers = splitList(await ask('允许的 user_openid（逗号分隔；未知可留空）：'))
    config.enableWhoami = true
    config.allowedTools = splitList(await ask('允许的宿主工具名（逗号分隔；默认不开放）：'))
    if (!env) resolveConfig(config, {})
    await saveOverlay(path, config, bundle)
    console.log(`已生成 ${path}`)
    if (env) console.log('启动 DSH 前，请设置 QQ_BOT_APP_ID 和 QQ_BOT_APP_SECRET。本工具不会自动读取 .env。')
    if (!config.allowGroups.length && !config.allowUsers.length) console.log('首次启动后发送 /whoami，复制返回的 OpenID 到此文件白名单。普通聊天暂不开放。')
    console.log(`检查：node ${JSON.stringify(resolve(root, 'scripts/cli.mjs'))} doctor --output ${JSON.stringify(path)}`)
    console.log(`启动：dsh${bundle ? ' --profile <已安装此插件的配置名>' : ' web'} --patch ${JSON.stringify(path)}`)
  } finally { rl.close() }
}
async function doctor(path) {
  let input
  try { input = readConfig(await readFile(path, 'utf8')) }
  catch { throw new Error('无法读取配置：确认文件存在、YAML 格式正确，且包含唯一的 qq-bot 条目；动态 !!js 配置请使用 DSH 自身检查。') }
  if (Config(input).enabled === false) {
    console.log('配置有效，QQ 连接已暂停；填写凭据后设置 enabled: true。')
    return
  }
  const config = resolveConfig(input)
  console.log('✓ 配置格式、凭据存在性和数值范围检查通过（未联网验证凭据）')
  console.log(`环境：${config.sandbox ? '沙箱' : '正式'}；群白名单 ${config.allowGroups.length} 项；用户白名单 ${config.allowUsers.length} 项；工具白名单 ${config.allowedTools.length} 项`)
  if (config.publicMode) console.log('提示：publicMode 已开启，所有 QQ 用户均可访问。')
  else if (!config.allowGroups.length && !config.allowUsers.length) console.log(config.enableWhoami === false
    ? '提示：白名单为空且身份发现关闭，机器人不会响应消息。'
    : '提示：白名单为空；先发送 /whoami 获取 OpenID，再加入白名单。')
  console.log('还需在 DSH 中确认默认 provider/model 与工具已加载，并在 QQ 平台配置测试群/用户。')
}
async function init(path, bundle) {
  await saveOverlay(path, {
    enabled: true,
    appId: '',
    clientSecret: '',
    sandbox: false,
    publicMode: false,
    allowGroups: [],
    allowUsers: [],
    enableWhoami: true,
    allowedTools: [],
    enableImages: true,
  }, bundle)
  console.log('已生成配置：' + path)
  console.log('启动 DSH 前设置 QQ_BOT_APP_ID 和 QQ_BOT_APP_SECRET，并配置默认 provider/model。')
  console.log('白名单为空；先发送 /whoami 获取 OpenID，再加入白名单。已有配置不会覆盖。')
}
export async function main(args) {
  const [command, ...options] = args
  if (!command || ['--help', '-h', 'help'].includes(command)) {
    console.log('用法：dsh-qq-bot setup|init|doctor [--output cordis.yml] [--bundle]\nsetup：引导生成配置；--bundle 为已安装 bundle 生成覆盖条目。\ninit：无需交互生成环境变量配置，适用于服务器；同样支持 --bundle。\ndoctor：离线检查配置，不输出凭据，不连接 QQ。')
    return
  }
  if (!['setup', 'init', 'doctor'].includes(command)) throw new Error('未知命令，请使用 --help。')
  let path = resolve('cordis.yml')
  let bundle = false
  for (let i = 0; i < options.length; i++) {
    if (options[i] === '--output' && options[i + 1] && !options[i + 1].startsWith('--')) path = resolve(options[++i])
    else if (options[i] === '--bundle' && ['setup', 'init'].includes(command)) bundle = true
    else throw new Error('未知或不完整的选项，请使用 --help。')
  }
  if (command === 'init') await init(path, bundle)
  else if (command === 'setup') await setup(path, bundle)
  else await doctor(path)
}
if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  main(process.argv.slice(2)).catch((error) => {
    console.error(error.code === 'EEXIST' ? '目标文件已存在，未覆盖。' : error.code ? '文件操作失败，请检查路径和权限。' : error.message)
    process.exitCode = 1
  })
}
